void-linux/void-packages@master:
  - source: ./*
    dest: void/
    with:
      BRANCH_PREFIX: void

Makrennel/hyprland-void@master:
  - source: ./**
    dest: hyprland/
    with:
      BRANCH_PREFIX: hyprland

index-0/librewolf-void@master:
  - source: ./**
    dest: librewolf/
    with:
      BRANCH_PREFIX: librewolf

mobinmob/abyss-packages@main:
  - source: ./**
    dest: abyss/
    with:
      BRANCH_PREFIX: abyss
