void-linux/void-packages@master:
  - source:
    "$VOID"
    dest: void/
    with:
      BRANCH_PREFIX: void

Makrennel/hyprland-void@master:
  - source:
    "$HYPRLAND"
    dest: hyprland/
    with:
      BRANCH_PREFIX: hyprland

index-0/librewolf-void@master:
  - source:
    "$LIBREWOLF"
    dest: librewolf/
    with:
      BRANCH_PREFIX: librewolf

mobinmob/abyss-packages@main:
  - source:
    "$ABYSS"
    dest: abyss/
    with:
      BRANCH_PREFIX: abyss
