name: Easy sync
on:
  push:
    paths:
      - .github/workflows/easy-sync.yml
      
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout
      - name: Run Sync
        with:
          GH_PAT: ${{ secrets.TOKEN }}
        run: |
          git clone https://github.com/void-linux/void-packages
          cd void-packages
          ./xbps-src binary-bootstrap
          cd ..
          git clone https://github.com/Makrennel/hyprland-void.git
          cd hyprland-void
          cat common/shlibs >> ../void-packages/common/shlibs
          cp -r --remove-destination srcpkgs/* ../void-packages/srcpkgs
          cd ../void-packages
          ./xbps-src pkg hyprland
